---
  - name: install python mysql bindings
    apt: name=python-mysqldb state=latest
    become: yes
    become_method: sudo

  - name: 'Install MySQL Server'
    apt: name={{ item }} state=latest
    with_items:
        - mysql-server
        - mysql-client
        - python-dev

  - name: Update MySQL root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
    with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost

  - name: Copy the root credentials as .my.cnf file
    template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
     - localhost
     - "{{ ansible_hostname }}"

  - name: create database
    mysql_db: name={{ db_name }} state=present

  - name: create user
    mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL
              host='%'
  - name: Remove the test database
    mysql_db: name=test state=absent
    notify:
     - restart MySQL